"""empty message

Revision ID: 89a6d6cdb887
Revises: 74d3d524494a
Create Date: 2023-02-25 18:23:38.570754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a6d6cdb887'
down_revision = '74d3d524494a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
